import { QuizQuestion, ThreatFeedItem, NewsItem, ScamAlert, AwarenessArticle, SecurityChecklistItem, FamilyMember, NotificationItem, ScamSimulation } from "./types";

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    heroTitle: "AI-Powered Cyber Fraud Prevention & Response Platform",
    heroSub: "Detect. Prevent. Respond. Protect yourself and your family from UPI scams, phishing, fake calls, malicious links, QR frauds, and financial cyber attacks using state-of-the-art Artificial Intelligence.",
    getStarted: "Get Started",
    reportFraud: "Report Fraud",
    tryAssistant: "Try AI Assistant",
    navHome: "Home",
    navFeatures: "Features",
    navScanner: "AI Scanner",
    navDashboard: "Dashboard",
    navReport: "Report Fraud",
    navResources: "Resources",
    navAbout: "About Us",
    navQuiz: "Cyber Quiz",
    navAwareness: "Cyber Awareness",
    navAlerts: "Scam Alerts",
    navFamily: "Family Protection",
    navSimulator: "Scam Simulator",
    navAdmin: "Admin Panel",
    navContact: "Contact",
    navPolice: "🚔 Police",
    navSos: "SOS ⚠️",
    navLearn: "Learn",
    navSosEmergency: "🚨 SOS Emergency",
    navLearnArticles: "📚 Learn & Articles",
    policeTitle: "Police Stations - Bhopal",
    policeSubtitle: "Find & contact police stations across Bhopal city",
    policeNoResults: "No police stations found matching your search.",
    policeClearFilters: "Clear filters",
    sosTitle: "Emergency Response System",
    sosSubtitle: "If you have been scammed or witnessed unauthorized debits, act immediately! Under the \"Golden Hour\" guideline, money transferred through UPI/IMPS can often be frozen before fraudsters withdraw it.",
    sosIAVictim: "⚠️ I am a Victim",
    sosHotlines: "Hotlines",
    sosBankFreeze: "Bank Freeze",
    sosFileFIR: "File FIR",
    sosEvidence: "Evidence",
    sosBlockSIM: "Block SIM",
    learnTitle: "Cyber Awareness Hub",
    learnSubtitle: "Stay informed with the latest cyber security articles, real-time scam alerts, interactive security checklists, video tutorials, and daily challenges.",
    learnArticles: "Articles",
    learnScamAlerts: "Scam Alerts",
    learnChecklist: "Security Checklist",
    learnVideos: "Video Learning",
    learnQuiz: "Daily Quiz",
    emergencyBtn: "Emergency Response (I am a Victim)",
    liveFeed: "Live Threat Intelligence Feed",
    interactiveMap: "Interactive National Fraud Density Map",
    cyberScore: "Your Personal Cyber Security Score",
    // Social Media Protection
    socialTitle: "Social Media Protection",
    socialDesc: "Protect yourself from fake profiles, scam messages, and investment fraud on social platforms. CyberSathi AI analyzes profiles and messages to detect impersonation, phishing, and fraudulent schemes.",
    socialTabProfile: "Fake Profile Detection",
    socialTabMessage: "Scam Message Analysis",
    socialInvestTitle: "Investment Scam Alerts",
    socialInvest1: "\"Guaranteed high returns\" on Telegram/WhatsApp groups are always scams. Only you are real — the rest are bots.",
    socialInvest2: "Fake trading apps (SBI Wealth Pro, etc.) promise 500% returns. Deposits are never returned.",
    socialInvest3: "Task-based job scams: small initial payments build trust, then \"investment tasks\" drain your bank.",
    socialInvest4: "Always verify schemes with SEBI-registered advisors. If it sounds too good to be true, it is.",
    socialWATitle: "WhatsApp / Telegram Safety Tips",
    socialWATip1: "Enable two-factor authentication on WhatsApp and Telegram.",
    socialWATip2: "Never share OTP, UPI PIN, or screen access with anyone on these platforms.",
    socialWATip3: "Verify financial requests via a phone call — not text on WhatsApp/Telegram.",
    socialWATip4: "Report scam accounts and groups to the platform immediately.",
    socialProfileUrl: "Social Profile URL / Handle",
    socialProfileName: "Display Name (optional)",
    socialProfilePlaceholder: "e.g. instagram.com/sbi_official_help or @fake_profile",
    socialProfileNamePlaceholder: "e.g. SBI Official Help",
    socialMessageLabel: "Paste suspicious social media message",
    socialMessagePlaceholder: "Paste the suspicious message from WhatsApp, Telegram, Instagram, Facebook, or Twitter...",
    socialQuickSample: "Quick Sample:",
    socialAnalyze: "🛡️ Analyze with CyberSathi AI",
    socialAnalyzing: "CyberSathi AI Analyzing...",
    socialReport: "SOCIAL SCAN REPORT",
    socialVerdictSafe: "Verdict: Legitimate & Safe",
    socialVerdictSuspicious: "Verdict: Suspicious Flags Found",
    socialVerdictFraud: "Verdict: Fraudulent / Scam Detected",
    socialRiskScore: "Risk Score:",
    socialThreatClass: "Threat Classification",
    socialHighlights: "Suspicious Text Highlights",
    socialForensic: "Forensic Analysis",
    socialRedFlags: "Red Flags Detected",
    socialDirectives: "CyberSathi Shield Directives",
    socialHowTitle: "How to Spot Social Media Scams",
    socialHowFake: "Fake Profiles",
    socialHowFake1: "Check follower count vs. engagement",
    socialHowFake2: "Look for verified badges (blue tick)",
    socialHowFake3: "Examine account creation date",
    socialHowFake4: "Watch for misspelled brand names",
    socialHowScam: "Scam Messages",
    socialHowScam1: "Unsolicited prize/giveaway claims",
    socialHowScam2: "Urgent requests for money/OTP",
    socialHowScam3: "Links to lookalike domains",
    socialHowScam4: "\"Limited time\" pressure tactics",
    socialHowInvest: "Investment Frauds",
    socialHowInvest1: "Guaranteed unrealistic returns",
    socialHowInvest2: "Telegram/WhatsApp group pressure",
    socialHowInvest3: "Fake profit screenshots from bots",
    socialHowInvest4: "Requests for upfront \"fees\"",
    socialHowSafe: "Platform Safety",
    socialHowSafe1: "Enable 2FA on all social accounts",
    socialHowSafe2: "Report suspicious profiles",
    socialHowSafe3: "Never share screen access",
    socialHowSafe4: "Verify through official channels",
    // Fraud Detection
    fraudTitle: "Fraud Detection Hub",
    fraudDesc: "Advanced tools to analyze transactions, verify UPI IDs, assess bank account risk, detect fake payment screenshots, and scan QR codes for security threats.",
    fraudTabTransaction: "Transaction Analysis",
    fraudTabUpi: "UPI ID Verification",
    fraudTabBank: "Bank Account Risk",
    fraudTabScreenshot: "Fake Screenshot Detection",
    fraudTabQr: "QR Code Security",
    fraudSafetyTitle: "Safety Reminders",
    fraudSafety1: "Never scan a QR code to \"receive\" money — QR codes are for sending payments.",
    fraudSafety2: "Always verify UPI IDs and bank accounts before making large transfers.",
    fraudSafety3: "Fake payment screenshots are common. Always confirm money in your account.",
    fraudTransactionLabel: "Transaction Details",
    fraudTransactionAmount: "Amount (INR)",
    fraudTransactionReceiver: "Receiver UPI / Account",
    fraudTransactionNote: "Transaction Note / Purpose",
    fraudTransactionAmtPlaceholder: "e.g. 5000",
    fraudTransactionRecPlaceholder: "e.g. receiver@paytm",
    fraudTransactionNotePlaceholder: "e.g. Tax refund processing fee, prize claim",
    fraudTransactionSample: "[Load Sample Scam Transaction]",
    fraudUpiLabel: "UPI ID to Verify",
    fraudUpiPlaceholder: "e.g. recipient@paytm or rewardclaim@icici",
    fraudUpiDesc: "Checks if the UPI ID is associated with known fraudulent patterns, scam reports, or suspicious activity.",
    fraudUpiSample: "[Load Sample Suspicious UPI]",
    fraudBankLabel: "Bank Account Details",
    fraudBankAccount: "Account Number",
    fraudBankIfsc: "IFSC Code",
    fraudBankAccountPlaceholder: "e.g. 123456789012",
    fraudBankIfscPlaceholder: "e.g. SBIN0001234",
    fraudBankDesc: "Assesses risk level of the bank account based on known fraud databases and pattern analysis.",
    fraudBankSample: "[Load Sample Account]",
    fraudScreenshotLabel: "Upload Payment Screenshot",
    fraudScreenshotLoaded: "✓ Screenshot Loaded for Analysis",
    fraudScreenshotUpload: "Upload payment receipt screenshot",
    fraudScreenshotFormat: "JPG, PNG format",
    fraudScreenshotClear: "Clear",
    fraudScreenshotDesc: "AI-powered forensic analysis detects forged, photoshopped, or fake payment screenshots used in UPI scams.",
    fraudScreenshotSample: "[Mock Fake Receipt]",
    fraudQrLabel: "QR Code Security Analysis",
    fraudQrUpload: "Upload QR Code Image",
    fraudQrFormat: "JPEG or PNG file",
    fraudQrAttached: "✓ QR Image Attached",
    fraudQrRemove: "Remove",
    fraudQrDecoded: "Decoded QR Payload",
    fraudQrPlaceholder: "e.g. upi://pay?pa=scamster@okhdfc&pn=PaytmUser&am=5000",
    fraudQrSample: "[Load Sample Scam QR]",
    fraudAnalyze: "🛡️ Analyze with CyberSathi AI",
    fraudAnalyzing: "CyberSathi AI Analyzing...",
    fraudReport: "FRAUD ANALYSIS REPORT",
    fraudVerdictSafe: "Verdict: Legitimate & Safe",
    fraudVerdictSuspicious: "Verdict: Suspicious Flags Found",
    fraudVerdictFraud: "Verdict: Fraudulent Activity Detected",
    fraudRiskScore: "Risk Score:",
    fraudThreatClass: "Threat Classification",
    fraudForensic: "Forensic Analysis",
    fraudRedFlags: "Red Flags Detected",
    fraudDirectives: "CyberSathi Shield Directives",
  },
  hi: {
    heroTitle: "एआई-संचालित साइबर धोखाधड़ी रोकथाम और प्रतिक्रिया मंच",
    heroSub: "पता लगाएं। रोकें। प्रतिक्रिया दें। कृत्रिम बुद्धिमत्ता (AI) का उपयोग करके यूपीआई (UPI) घोटाले, फ़िशिंग, फर्जी कॉल, दुर्भावनापूर्ण लिंक, क्यूआर घोटाले और वित्तीय साइबर हमलों से खुद को और अपने परिवार को सुरक्षित रखें।",
    getStarted: "शुरू करें",
    reportFraud: "धोखाधड़ी की रिपोर्ट करें",
    tryAssistant: "एआई सहायक से बात करें",
    navHome: "मुख्य पृष्ठ",
    navFeatures: "विशेषताएं",
    navScanner: "एआई स्कैनर",
    navDashboard: "डैशबोर्ड",
    navReport: "रिपोर्ट करें",
    navResources: "संसाधन",
    navAbout: "हमारे बारे में",
    navQuiz: "साइबर क्विज़",
    navAwareness: "साइबर जागरूकता",
    navAlerts: "स्कैम अलर्ट",
    navFamily: "परिवार सुरक्षा",
    navSimulator: "स्कैम सिम्युलेटर",
    navAdmin: "एडमिन पैनल",
    navContact: "संपर्क",
    navPolice: "🚔 पुलिस",
    navSos: "एसओएस ⚠️",
    navLearn: "सीखें",
    navSosEmergency: "🚨 एसओएस आपातकाल",
    navLearnArticles: "📚 सीखें और लेख",
    policeTitle: "पुलिस स्टेशन - भोपाल",
    policeSubtitle: "भोपाल शहर भर में पुलिस स्टेशन खोजें और संपर्क करें",
    policeNoResults: "आपकी खोज से मेल खाने वाला कोई पुलिस स्टेशन नहीं मिला।",
    policeClearFilters: "फ़िल्टर साफ़ करें",
    sosTitle: "आपातकालीन प्रतिक्रिया प्रणाली",
    sosSubtitle: "यदि आपके साथ धोखाधड़ी हुई है या आपने अनधिकृत डेबिट देखा है, तो तुरंत कार्रवाई करें! 'गोल्डन ऑवर' दिशानिर्देश के तहत, UPI/IMPS के माध्यम से स्थानांतरित धन को अक्सर धोखेबाजों द्वारा निकालने से पहले फ्रीज किया जा सकता है।",
    sosIAVictim: "⚠️ मैं पीड़ित हूँ",
    sosHotlines: "हॉटलाइन",
    sosBankFreeze: "बैंक फ्रीज",
    sosFileFIR: "एफआईआर दर्ज करें",
    sosEvidence: "सबूत",
    sosBlockSIM: "सिम ब्लॉक करें",
    learnTitle: "साइबर जागरूकता केंद्र",
    learnSubtitle: "नवीनतम साइबर सुरक्षा लेखों, रीयल-टाइम स्कैम अलर्ट, इंटरैक्टिव सुरक्षा चेकलिस्ट, वीडियो ट्यूटोरियल और दैनिक चुनौतियों के साथ अपडेट रहें।",
    learnArticles: "लेख",
    learnScamAlerts: "स्कैम अलर्ट",
    learnChecklist: "सुरक्षा चेकलिस्ट",
    learnVideos: "वीडियो सीखना",
    learnQuiz: "दैनिक क्विज़",
    emergencyBtn: "आपातकालीन प्रतिक्रिया (मैं पीड़ित हूँ)",
    liveFeed: "लाइव साइबर खतरा चेतावनी फ़ीड",
    interactiveMap: "इंटरैक्टिव राष्ट्रीय साइबर धोखाधड़ी मानचित्र",
    cyberScore: "आपका साइबर सुरक्षा स्कोर",
    // Social Media Protection
    socialTitle: "सोशल मीडिया सुरक्षा",
    socialDesc: "सोशल प्लेटफॉर्म पर फर्जी प्रोफाइल, स्कैम संदेशों और निवेश धोखाधड़ी से खुद को बचाएं। साइबरसाथी AI फर्जीवाड़े, फ़िशिंग और धोखाधड़ी योजनाओं का पता लगाने के लिए प्रोफाइल और संदेशों का विश्लेषण करता है।",
    socialTabProfile: "फर्जी प्रोफाइल का पता लगाएं",
    socialTabMessage: "स्कैम संदेश विश्लेषण",
    socialInvestTitle: "निवेश स्कैम अलर्ट",
    socialInvest1: "Telegram/WhatsApp ग्रुप पर 'गारंटीड हाई रिटर्न' हमेशा स्कैम होते हैं। केवल आप असली हैं — बाकी सब बॉट हैं।",
    socialInvest2: "फर्जी ट्रेडिंग ऐप (SBI Wealth Pro, आदि) 500% रिटर्न का वादा करते हैं। जमा राशि कभी वापस नहीं मिलती।",
    socialInvest3: "टास्क-आधारित जॉब स्कैम: छोटे शुरुआती भुगतान विश्वास बनाते हैं, फिर 'निवेश कार्य' आपका बैंक खाली कर देते हैं।",
    socialInvest4: "SEBI-पंजीकृत सलाहकारों के साथ योजनाओं की हमेशा पुष्टि करें। अगर यह सच होने के लिए बहुत अच्छा लगता है, तो यह है।",
    socialWATitle: "WhatsApp / Telegram सुरक्षा टिप्स",
    socialWATip1: "WhatsApp और Telegram पर टू-फैक्टर ऑथेंटिकेशन चालू करें।",
    socialWATip2: "इन प्लेटफॉर्म पर किसी के साथ OTP, UPI PIN या स्क्रीन एक्सेस कभी साझा न करें।",
    socialWATip3: "WhatsApp/Telegram पर टेक्स्ट के बजाय फोन कॉल करके वित्तीय अनुरोधों की पुष्टि करें।",
    socialWATip4: "स्कैम खातों और ग्रुप्स की तुरंत प्लेटफॉर्म पर रिपोर्ट करें।",
    socialProfileUrl: "सोशल प्रोफाइल URL / हैंडल",
    socialProfileName: "प्रदर्शित नाम (वैकल्पिक)",
    socialProfilePlaceholder: "जैसे instagram.com/sbi_official_help या @fake_profile",
    socialProfileNamePlaceholder: "जैसे SBI Official Help",
    socialMessageLabel: "संदिग्ध सोशल मीडिया संदेश चिपकाएं",
    socialMessagePlaceholder: "WhatsApp, Telegram, Instagram, Facebook या Twitter से संदिग्ध संदेश चिपकाएं...",
    socialQuickSample: "त्वरित नमूना:",
    socialAnalyze: "🛡️ CyberSathi AI से विश्लेषण करें",
    socialAnalyzing: "CyberSathi AI विश्लेषण कर रहा है...",
    socialReport: "सोशल स्कैन रिपोर्ट",
    socialVerdictSafe: "निर्णय: वैध और सुरक्षित",
    socialVerdictSuspicious: "निर्णय: संदिग्ध ध्वज मिले",
    socialVerdictFraud: "निर्णय: धोखाधड़ी/स्कैम का पता चला",
    socialRiskScore: "जोखिम स्कोर:",
    socialThreatClass: "खतरा वर्गीकरण",
    socialHighlights: "संदिग्ध टेक्स्ट हाइलाइट्स",
    socialForensic: "फोरेंसिक विश्लेषण",
    socialRedFlags: "पाए गए लाल झंडे",
    socialDirectives: "CyberSathi Shield निर्देश",
    socialHowTitle: "सोशल मीडिया स्कैम की पहचान कैसे करें",
    socialHowFake: "फर्जी प्रोफाइल",
    socialHowFake1: "फॉलोअर काउंट बनाम एंगेजमेंट चेक करें",
    socialHowFake2: "वेरिफाइड बैज (नीला टिक) देखें",
    socialHowFake3: "खाता निर्माण तिथि जांचें",
    socialHowFake4: "गलत वर्तनी वाले ब्रांड नामों से सावधान रहें",
    socialHowScam: "स्कैम संदेश",
    socialHowScam1: "अनचाहे पुरस्कार/गिवअवे दावे",
    socialHowScam2: "पैसे/OTP के लिए तत्काल अनुरोध",
    socialHowScam3: "नकली डोमेन के लिंक",
    socialHowScam4: "'सीमित समय' दबाव रणनीति",
    socialHowInvest: "निवेश धोखाधड़ी",
    socialHowInvest1: "गारंटीकृत अवास्तविक रिटर्न",
    socialHowInvest2: "Telegram/WhatsApp ग्रुप दबाव",
    socialHowInvest3: "बॉट्स से फर्जी लाभ स्क्रीनशॉट",
    socialHowInvest4: "अग्रिम 'शुल्क' के अनुरोध",
    socialHowSafe: "प्लेटफॉर्म सुरक्षा",
    socialHowSafe1: "सभी सोशल खातों पर 2FA चालू करें",
    socialHowSafe2: "संदिग्ध प्रोफाइल रिपोर्ट करें",
    socialHowSafe3: "स्क्रीन एक्सेस कभी साझा न करें",
    socialHowSafe4: "आधिकारिक चैनलों के माध्यम से पुष्टि करें",
    // Fraud Detection
    fraudTitle: "धोखाधड़ी का पता लगाने वाला हब",
    fraudDesc: "लेन-देन का विश्लेषण करने, UPI ID सत्यापित करने, बैंक खाता जोखिम का आकलन करने, फर्जी भुगतान स्क्रीनशॉट का पता लगाने और सुरक्षा खतरों के लिए QR कोड स्कैन करने के लिए उन्नत उपकरण।",
    fraudTabTransaction: "लेन-देन विश्लेषण",
    fraudTabUpi: "UPI ID सत्यापन",
    fraudTabBank: "बैंक खाता जोखिम",
    fraudTabScreenshot: "फर्जी स्क्रीनशॉट का पता लगाएं",
    fraudTabQr: "QR कोड सुरक्षा",
    fraudSafetyTitle: "सुरक्षा अनुस्मारक",
    fraudSafety1: "पैसे 'प्राप्त' करने के लिए कभी QR कोड स्कैन न करें — QR कोड भेजने के लिए होते हैं।",
    fraudSafety2: "बड़े ट्रांसफर करने से पहले हमेशा UPI ID और बैंक खातों की पुष्टि करें।",
    fraudSafety3: "फर्जी भुगतान स्क्रीनशॉट आम हैं। हमेशा अपने खाते में पैसे की पुष्टि करें।",
    fraudTransactionLabel: "लेन-देन विवरण",
    fraudTransactionAmount: "राशि (INR)",
    fraudTransactionReceiver: "प्राप्तकर्ता UPI / खाता",
    fraudTransactionNote: "लेन-देन नोट / उद्देश्य",
    fraudTransactionAmtPlaceholder: "जैसे 5000",
    fraudTransactionRecPlaceholder: "जैसे receiver@paytm",
    fraudTransactionNotePlaceholder: "जैसे टैक्स रिफंड प्रोसेसिंग फीस, पुरस्कार दावा",
    fraudTransactionSample: "[नमूना स्कैम लेन-देन लोड करें]",
    fraudUpiLabel: "सत्यापित करने के लिए UPI ID",
    fraudUpiPlaceholder: "जैसे recipient@paytm या rewardclaim@icici",
    fraudUpiDesc: "जांचता है कि UPI ID ज्ञात धोखाधड़ी पैटर्न, स्कैम रिपोर्ट या संदिग्ध गतिविधि से जुड़ा है या नहीं।",
    fraudUpiSample: "[संदिग्ध UPI का नमूना लोड करें]",
    fraudBankLabel: "बैंक खाता विवरण",
    fraudBankAccount: "खाता संख्या",
    fraudBankIfsc: "IFSC कोड",
    fraudBankAccountPlaceholder: "जैसे 123456789012",
    fraudBankIfscPlaceholder: "जैसे SBIN0001234",
    fraudBankDesc: "ज्ञात धोखाधड़ी डेटाबेस और पैटर्न विश्लेषण के आधार पर बैंक खाते के जोखिम स्तर का आकलन करता है।",
    fraudBankSample: "[नमूना खाता लोड करें]",
    fraudScreenshotLabel: "भुगतान स्क्रीनशॉट अपलोड करें",
    fraudScreenshotLoaded: "✓ विश्लेषण के लिए स्क्रीनशॉट लोड किया गया",
    fraudScreenshotUpload: "भुगतान रसीद स्क्रीनशॉट अपलोड करें",
    fraudScreenshotFormat: "JPG, PNG फॉर्मेट",
    fraudScreenshotClear: "हटाएं",
    fraudScreenshotDesc: "AI-संचालित फोरेंसिक विश्लेषण UPI स्कैम में उपयोग किए जाने वाले नकली, फोटोशॉप या फर्जी भुगतान स्क्रीनशॉट का पता लगाता है।",
    fraudScreenshotSample: "[नकली रसीद]",
    fraudQrLabel: "QR कोड सुरक्षा विश्लेषण",
    fraudQrUpload: "QR कोड छवि अपलोड करें",
    fraudQrFormat: "JPEG या PNG फ़ाइल",
    fraudQrAttached: "✓ QR छवि संलग्न",
    fraudQrRemove: "हटाएं",
    fraudQrDecoded: "डिकोड किया गया QR पेलोड",
    fraudQrPlaceholder: "जैसे upi://pay?pa=scamster@okhdfc&pn=PaytmUser&am=5000",
    fraudQrSample: "[नमूना स्कैम QR लोड करें]",
    fraudAnalyze: "🛡️ CyberSathi AI से विश्लेषण करें",
    fraudAnalyzing: "CyberSathi AI विश्लेषण कर रहा है...",
    fraudReport: "धोखाधड़ी विश्लेषण रिपोर्ट",
    fraudVerdictSafe: "निर्णय: वैध और सुरक्षित",
    fraudVerdictSuspicious: "निर्णय: संदिग्ध ध्वज मिले",
    fraudVerdictFraud: "निर्णय: धोखाधड़ी गतिविधि का पता चला",
    fraudRiskScore: "जोखिम स्कोर:",
    fraudThreatClass: "खतरा वर्गीकरण",
    fraudForensic: "फोरेंसिक विश्लेषण",
    fraudRedFlags: "पाए गए लाल झंडे",
    fraudDirectives: "CyberSathi Shield निर्देश",
  },
  bn: {
    heroTitle: "এআই-চালিত সাইবার জালিয়াতি প্রতিরোধ ও প্রতিক্রিয়া প্ল্যাটফর্ম",
    heroSub: "শনাক্ত করুন। প্রতিরোধ করুন। প্রতিক্রিয়া জানান। অত্যাধুনিক কৃত্রিম বুদ্ধিমত্তা ব্যবহার করে ইউপিআই জালিয়াতি, ফিশিং, জাল কল, দূষিত লিংক, কিউআর জালিয়াতি এবং আর্থিক সাইবার আক্রমণ থেকে নিজেকে এবং আপনার পরিবারকে রক্ষা করুন।",
    getStarted: "শুরু করুন",
    reportFraud: "জালিয়াতি রিপোর্ট করুন",
    tryAssistant: "এআই সহায়ক ব্যবহার করুন",
    navHome: "হোম",
    navFeatures: "বৈশিষ্ট্য",
    navScanner: "এআই স্ক্যানার",
    navDashboard: "ড্যাশবোর্ড",
    navReport: "রিপোর্ট করুন",
    navResources: "সম্পদ",
    navAbout: "আমাদের সম্পর্কে",
    navPolice: "🚔 পুলিশ",
    navSos: "এসওএস ⚠️",
    navLearn: "শিখুন",
    navSosEmergency: "🚨 এসওএস জরুরি",
    navLearnArticles: "📚 শিখুন ও নিবন্ধ",
    policeTitle: "পুলিশ স্টেশন - ভোপাল",
    policeSubtitle: "ভোপাল শহর জুড়ে পুলিশ স্টেশন খুঁজুন ও যোগাযোগ করুন",
    policeNoResults: "আপনার অনুসন্ধানের সাথে মিলে যাওয়া কোনো পুলিশ স্টেশন পাওয়া যায়নি।",
    policeClearFilters: "ফিল্টার পরিষ্কার করুন",
    sosTitle: "জরুরি প্রতিক্রিয়া ব্যবস্থা",
    sosSubtitle: "যদি আপনার সাথে জালিয়াতি হয়ে থাকে বা আপনি অননুমোদিত ডেবিট দেখে থাকেন, তাহলে অবিলম্বে কাজ করুন! 'গোল্ডেন আওয়ার' নির্দেশিকা অনুসারে, UPI/IMPS-এর মাধ্যমে স্থানান্তরিত টাকা প্রতারকরা তোলার আগেই প্রায়শই ফ্রিজ করা যেতে পারে।",
    sosIAVictim: "⚠️ আমি শিকার",
    sosHotlines: "হটলাইন",
    sosBankFreeze: "ব্যাংক ফ্রিজ",
    sosFileFIR: "এফআইআর দায়ের করুন",
    sosEvidence: "প্রমাণ",
    sosBlockSIM: "সিম ব্লক করুন",
    learnTitle: "সাইবার সচেতনতা কেন্দ্র",
    learnSubtitle: "সর্বশেষ সাইবার নিরাপত্তা নিবন্ধ, রিয়েল-টাইম স্ক্যাম সতর্কতা, ইন্টারেক্টিভ নিরাপত্তা চেকলিস্ট, ভিডিও টিউটোরিয়াল এবং দৈনিক চ্যালেঞ্জের সাথে আপডেট থাকুন।",
    learnArticles: "নিবন্ধ",
    learnScamAlerts: "স্ক্যাম সতর্কতা",
    learnChecklist: "নিরাপত্তা চেকলিস্ট",
    learnVideos: "ভিডিও শেখা",
    learnQuiz: "দৈনিক কুইজ",
    emergencyBtn: "জরুরি প্রতিক্রিয়া (আমি শিকার)",
    navQuiz: "সাইবার কুইজ",
    navAwareness: "সাইবার সচেতনতা",
    navAlerts: "স্ক্যাম সতর্কতা",
    navFamily: "পরিবার সুরক্ষা",
    navSimulator: "স্ক্যাম সিমুলেটর",
    navAdmin: "অ্যাডমিন প্যানেল",
    navContact: "যোগাযোগ",
    liveFeed: "লাইভ সাইবার হুমকি ইন্টেলিজেন্স ফিড",
    interactiveMap: "ইন্টারেক্টিভ জাতীয় সাইবার জালিয়াতি ঘনত্ব মানচিত্র",
    cyberScore: "আপনার ব্যক্তিগত সাইবার নিরাপত্তা স্কোর",
    // Social Media Protection
    socialTitle: "সোশ্যাল মিডিয়া সুরক্ষা",
    socialDesc: "সোশ্যাল প্ল্যাটফর্মে জাল প্রোফাইল, স্ক্যাম বার্তা এবং বিনিয়োগ জালিয়াতি থেকে নিজেকে রক্ষা করুন। CyberSathi AI প্রতারণা, ফিশিং এবং জালিয়াতি পরিকল্পনা সনাক্ত করতে প্রোফাইল এবং বার্তা বিশ্লেষণ করে।",
    socialTabProfile: "জাল প্রোফাইল সনাক্তকরণ",
    socialTabMessage: "স্ক্যাম বার্তা বিশ্লেষণ",
    socialInvestTitle: "বিনিয়োগ স্ক্যাম সতর্কতা",
    socialInvest1: "Telegram/WhatsApp গ্রুপে 'গ্যারান্টিযুক্ত উচ্চ রিটার্ন' সবসময় স্ক্যাম। শুধু আপনিই আসল — বাকিরা সব বট।",
    socialInvest2: "জাল ট্রেডিং অ্যাপ (SBI Wealth Pro, ইত্যাদি) 500% রিটার্নের প্রতিশ্রুতি দেয়। জমা কখনও ফেরত দেওয়া হয় না।",
    socialInvest3: "টাস্ক-ভিত্তিক চাকরির স্ক্যাম: ছোট প্রাথমিক পেমেন্ট বিশ্বাস তৈরি করে, তারপর 'বিনিয়োগ টাস্ক' আপনার ব্যাংক খালি করে দেয়।",
    socialInvest4: "SEBI-নিবন্ধিত উপদেষ্টাদের সাথে সর্বদা পরিকল্পনা যাচাই করুন। যদি এটি সত্য হতে খুব ভালো শোনায়, তবে তা তাই।",
    socialWATitle: "WhatsApp / Telegram সুরক্ষা টিপস",
    socialWATip1: "WhatsApp এবং Telegram-এ টু-ফ্যাক্টর অথেন্টিকেশন চালু করুন।",
    socialWATip2: "এই প্ল্যাটফর্মগুলিতে কারোর সাথে OTP, UPI PIN বা স্ক্রিন অ্যাক্সেস কখনও শেয়ার করবেন না।",
    socialWATip3: "WhatsApp/Telegram-এ টেক্সটের পরিবর্তে ফোন কলের মাধ্যমে আর্থিক অনুরোধ যাচাই করুন।",
    socialWATip4: "স্ক্যাম অ্যাকাউন্ট এবং গ্রুপগুলি তৎক্ষণাৎ প্ল্যাটফর্মে রিপোর্ট করুন।",
    socialProfileUrl: "সোশ্যাল প্রোফাইল URL / হ্যান্ডেল",
    socialProfileName: "প্রদর্শনের নাম (ঐচ্ছিক)",
    socialProfilePlaceholder: "যেমন instagram.com/sbi_official_help বা @fake_profile",
    socialProfileNamePlaceholder: "যেমন SBI Official Help",
    socialMessageLabel: "সন্দেহজনক সোশ্যাল মিডিয়া বার্তা পেস্ট করুন",
    socialMessagePlaceholder: "WhatsApp, Telegram, Instagram, Facebook বা Twitter থেকে সন্দেহজনক বার্তা পেস্ট করুন...",
    socialQuickSample: "দ্রুত নমুনা:",
    socialAnalyze: "🛡️ CyberSathi AI দিয়ে বিশ্লেষণ করুন",
    socialAnalyzing: "CyberSathi AI বিশ্লেষণ করছে...",
    socialReport: "সোশ্যাল স্ক্যান রিপোর্ট",
    socialVerdictSafe: "রায়: বৈধ এবং নিরাপদ",
    socialVerdictSuspicious: "রায়: সন্দেহজনক ফ্ল্যাগ পাওয়া গেছে",
    socialVerdictFraud: "রায়: জালিয়াতি / স্ক্যাম সনাক্ত হয়েছে",
    socialRiskScore: "ঝুঁকি স্কোর:",
    socialThreatClass: "হুমকি শ্রেণীবিভাগ",
    socialHighlights: "সন্দেহজনক টেক্সট হাইলাইটস",
    socialForensic: "ফরেনসিক বিশ্লেষণ",
    socialRedFlags: "সনাক্ত করা রেড ফ্ল্যাগ",
    socialDirectives: "CyberSathi Shield নির্দেশনা",
    socialHowTitle: "সোশ্যাল মিডিয়া স্ক্যাম চিনবেন কীভাবে",
    socialHowFake: "জাল প্রোফাইল",
    socialHowFake1: "ফলোয়ার কাউন্ট বনাম এনগেজমেন্ট চেক করুন",
    socialHowFake2: "ভেরিফাইড ব্যাজ (নীল টিক) দেখুন",
    socialHowFake3: "অ্যাকাউন্ট তৈরির তারিখ পরীক্ষা করুন",
    socialHowFake4: "ভুল বানানের ব্র্যান্ড নাম থেকে সাবধান",
    socialHowScam: "স্ক্যাম বার্তা",
    socialHowScam1: "অনিচ্ছাকৃত পুরস্কার/গিভঅয়ে দাবি",
    socialHowScam2: "টাকা/OTP-এর জন্য জরুরি অনুরোধ",
    socialHowScam3: "নকল ডোমেনের লিঙ্ক",
    socialHowScam4: "'সীমিত সময়' চাপের কৌশল",
    socialHowInvest: "বিনিয়োগ জালিয়াতি",
    socialHowInvest1: "গ্যারান্টিযুক্ত অবাস্তব রিটার্ন",
    socialHowInvest2: "Telegram/WhatsApp গ্রুপের চাপ",
    socialHowInvest3: "বট থেকে জাল লাভের স্ক্রিনশট",
    socialHowInvest4: "অগ্রিম 'ফি'র অনুরোধ",
    socialHowSafe: "প্ল্যাটফর্ম নিরাপত্তা",
    socialHowSafe1: "সব সোশ্যাল অ্যাকাউন্টে 2FA চালু করুন",
    socialHowSafe2: "সন্দেহজনক প্রোফাইল রিপোর্ট করুন",
    socialHowSafe3: "স্ক্রিন অ্যাক্সেস কখনও শেয়ার করবেন না",
    socialHowSafe4: "অফিসিয়াল চ্যানেলের মাধ্যমে নিশ্চিত করুন",
    // Fraud Detection
    fraudTitle: "জালিয়াতি সনাক্তকরণ হাব",
    fraudDesc: "লেনদেন বিশ্লেষণ, UPI ID যাচাই, ব্যাংক অ্যাকাউন্ট ঝুঁকি মূল্যায়ন, জাল পেমেন্ট স্ক্রিনশট সনাক্তকরণ এবং নিরাপত্তা হুমকির জন্য QR কোড স্ক্যান করার জন্য উন্নত টুল।",
    fraudTabTransaction: "লেনদেন বিশ্লেষণ",
    fraudTabUpi: "UPI ID যাচাইকরণ",
    fraudTabBank: "ব্যাংক অ্যাকাউন্ট ঝুঁকি",
    fraudTabScreenshot: "জাল স্ক্রিনশট সনাক্তকরণ",
    fraudTabQr: "QR কোড নিরাপত্তা",
    fraudSafetyTitle: "নিরাপত্তা স্মারক",
    fraudSafety1: "টাকা 'প্রাপ্তির' জন্য কখনও QR কোড স্ক্যান করবেন না — QR কোড পাঠানোর জন্য।",
    fraudSafety2: "বড় লেনদেনের আগে সর্বদা UPI ID এবং ব্যাংক অ্যাকাউন্ট যাচাই করুন।",
    fraudSafety3: "জাল পেমেন্ট স্ক্রিনশট সাধারণ। সর্বদা আপনার অ্যাকাউন্টে টাকা নিশ্চিত করুন।",
    fraudTransactionLabel: "লেনদেনের বিবরণ",
    fraudTransactionAmount: "পরিমাণ (INR)",
    fraudTransactionReceiver: "প্রাপক UPI / অ্যাকাউন্ট",
    fraudTransactionNote: "লেনদেন নোট / উদ্দেশ্য",
    fraudTransactionAmtPlaceholder: "যেমন 5000",
    fraudTransactionRecPlaceholder: "যেমন receiver@paytm",
    fraudTransactionNotePlaceholder: "যেমন ট্যাক্স রিফান্ড প্রসেসিং ফি, পুরস্কার দাবি",
    fraudTransactionSample: "[নমুনা স্ক্যাম লেনদেন লোড করুন]",
    fraudUpiLabel: "যাচাই করার জন্য UPI ID",
    fraudUpiPlaceholder: "যেমন recipient@paytm বা rewardclaim@icici",
    fraudUpiDesc: "পরীক্ষা করে যে UPI ID পরিচিত জালিয়াতি প্যাটার্ন, স্ক্যাম রিপোর্ট বা সন্দেহজনক কার্যকলাপের সাথে যুক্ত কিনা।",
    fraudUpiSample: "[সন্দেহজনক UPI নমুনা লোড করুন]",
    fraudBankLabel: "ব্যাংক অ্যাকাউন্টের বিবরণ",
    fraudBankAccount: "অ্যাকাউন্ট নম্বর",
    fraudBankIfsc: "IFSC কোড",
    fraudBankAccountPlaceholder: "যেমন 123456789012",
    fraudBankIfscPlaceholder: "যেমন SBIN0001234",
    fraudBankDesc: "পরিচিত জালিয়াতি ডাটাবেস এবং প্যাটার্ন বিশ্লেষণের ভিত্তিতে ব্যাংক অ্যাকাউন্টের ঝুঁকি স্তর মূল্যায়ন করে।",
    fraudBankSample: "[নমুনা অ্যাকাউন্ট লোড করুন]",
    fraudScreenshotLabel: "পেমেন্ট স্ক্রিনশট আপলোড করুন",
    fraudScreenshotLoaded: "✓ বিশ্লেষণের জন্য স্ক্রিনশট লোড করা হয়েছে",
    fraudScreenshotUpload: "পেমেন্ট রসিদ স্ক্রিনশট আপলোড করুন",
    fraudScreenshotFormat: "JPG, PNG ফরম্যাট",
    fraudScreenshotClear: "মুছুন",
    fraudScreenshotDesc: "AI-চালিত ফরেনসিক বিশ্লেষণ UPI স্ক্যামে ব্যবহৃত জাল, ফটোশপ বা নকল পেমেন্ট স্ক্রিনশট সনাক্ত করে।",
    fraudScreenshotSample: "[নকল রসিদ]",
    fraudQrLabel: "QR কোড নিরাপত্তা বিশ্লেষণ",
    fraudQrUpload: "QR কোড ছবি আপলোড করুন",
    fraudQrFormat: "JPEG বা PNG ফাইল",
    fraudQrAttached: "✓ QR ছবি সংযুক্ত",
    fraudQrRemove: "সরান",
    fraudQrDecoded: "ডিকোড করা QR পেলোড",
    fraudQrPlaceholder: "যেমন upi://pay?pa=scamster@okhdfc&pn=PaytmUser&am=5000",
    fraudQrSample: "[নমুনা স্ক্যাম QR লোড করুন]",
    fraudAnalyze: "🛡️ CyberSathi AI দিয়ে বিশ্লেষণ করুন",
    fraudAnalyzing: "CyberSathi AI বিশ্লেষণ করছে...",
    fraudReport: "জালিয়াতি বিশ্লেষণ রিপোর্ট",
    fraudVerdictSafe: "রায়: বৈধ এবং নিরাপদ",
    fraudVerdictSuspicious: "রায়: সন্দেহজনক ফ্ল্যাগ পাওয়া গেছে",
    fraudVerdictFraud: "রায়: জালিয়াতিমূলক কার্যকলাপ সনাক্ত হয়েছে",
    fraudRiskScore: "ঝুঁকি স্কোর:",
    fraudThreatClass: "হুমকি শ্রেণীবিভাগ",
    fraudForensic: "ফরেনসিক বিশ্লেষণ",
    fraudRedFlags: "সনাক্ত করা রেড ফ্ল্যাগ",
    fraudDirectives: "CyberSathi Shield নির্দেশনা",
  }
};

export const INDIA_STATE_STATS = [
  { id: "IN-JH", name: "Jharkhand (Jamtara)", threatIndex: 98, activeScams: "OTP scams, Bank KYC phishing", hotspots: ["Jamtara", "Deoghar"], color: "#EF4444" },
  { id: "IN-HR", name: "Haryana (Nuh/Mewat)", threatIndex: 94, activeScams: "Olx fake army payments, Sextortion", hotspots: ["Nuh", "Mewat", "Gurugram"], color: "#F59E0B" },
  { id: "IN-RJ", name: "Rajasthan (Bharatpur)", threatIndex: 89, activeScams: "Fake government schemes, QR Pay", hotspots: ["Bharatpur", "Alwar"], color: "#F59E0B" },
  { id: "IN-DL", name: "Delhi NCR", threatIndex: 85, activeScams: "Customs gift scams, Fake job portals", hotspots: ["Noida", "Dwarka", "South Delhi"], color: "#F59E0B" },
  { id: "IN-MH", name: "Maharashtra", threatIndex: 78, activeScams: "Electricity bill blocks, Part-time job scams", hotspots: ["Mumbai Suburbs", "Pune"], color: "#3B82F6" },
  { id: "IN-KA", name: "Karnataka", threatIndex: 72, activeScams: "Aadhar card leaks, Fake crypto investments", hotspots: ["Bengaluru East", "Mangaluru"], color: "#3B82F6" },
  { id: "IN-UP", name: "Uttar Pradesh", threatIndex: 81, activeScams: "Pension update fraud, SIM swap", hotspots: ["Ghaziabad", "Kanpur", "Lucknow"], color: "#F59E0B" },
  { id: "IN-WB", name: "West Bengal", threatIndex: 76, activeScams: "Lottery scams, Fake customer service numbers", hotspots: ["Kolkata", "Siliguri"], color: "#3B82F6" },
  { id: "IN-GJ", name: "Gujarat", threatIndex: 70, activeScams: "Fake investment apps, Property fraud", hotspots: ["Ahmedabad", "Surat"], color: "#3B82F6" },
  { id: "IN-TN", name: "Tamil Nadu", threatIndex: 68, activeScams: "Job offer scams, Loan app harassment", hotspots: ["Chennai", "Coimbatore"], color: "#22C55E" }
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "You receive an SMS: 'Your Electricity Power will be disconnected tonight. Call Helpline: 98765-XXXXX immediately.' What is the safest course of action?",
    options: [
      "Call the mobile number in the SMS to check why it's getting blocked.",
      "Ignore it entirely, or verify by visiting your electricity provider's official portal/app directly.",
      "Click the link to download the 'AnyDesk' utility suggested by the support officer.",
      "Pay the small pending fee instantly via UPI to prevent cutoff."
    ],
    correctIndex: 1,
    explanation: "This is a classic utility bill scam. Legitimate companies never send disconnections from standard personal mobile numbers nor demand immediate app downloads like AnyDesk."
  },
  {
    id: 2,
    question: "Do you need to enter your UPI PIN to receive money into your bank account?",
    options: [
      "Yes, the UPI PIN authorizes all transactions, both sending and receiving.",
      "Only if the sender is from a different bank or UPI application.",
      "No! UPI PIN is strictly used to AUTHORIZE DEBITS. You never need a PIN to receive funds.",
      "Yes, but only for transactions above INR 10,000."
    ],
    correctIndex: 2,
    explanation: "Scammers send 'Receive Money Request' links to victims. Scanning this and typing your UPI PIN will immediately deduct money from your account!"
  },
  {
    id: 3,
    question: "You receive a phone call from someone claiming to be a Customs Officer in Mumbai, saying a parcel with drugs/contraband has been found under your name and they face 'digital arrest'. They tell you to stay on a Skype call. What is this?",
    options: [
      "A real police investigation. I must follow instructions immediately to avoid arrest.",
      "A classic 'Digital Arrest' scam. Police never arrest anyone via Skype/Zoom nor request secret transfers.",
      "A minor administrative mix-up. I should transfer money to verify my funds.",
      "A package delivery update from FedEx."
    ],
    correctIndex: 1,
    explanation: "Law enforcement authorities do not conduct investigations on Zoom/Skype, keep citizens in 'digital arrest', or demand immediate financial transfer to verify funds."
  },
  {
    id: 4,
    question: "Which of the following websites is the OFFICIAL portal to report cyber fraud in India?",
    options: [
      "www.cybercrime.gov.in",
      "www.cyber-police-india.net",
      "www.sanchar-saathi-complaints.org",
      "www.indian-cyber-cell.in"
    ],
    correctIndex: 0,
    explanation: "cybercrime.gov.in is the only official government portal run by the Ministry of Home Affairs to file cyber complaints."
  },
  {
    id: 5,
    question: "A website URL displays 'https://www.onlinesbi-secure-update.com/login'. Is this safe?",
    options: [
      "Yes, because it starts with 'https://' which means it is encrypted and safe.",
      "No, because 'onlinesbi-secure-update.com' is a lookalike domain. The official domain is onlinesbi.sbi or sbi.co.in.",
      "Yes, because it contains the keyword 'onlinesbi'.",
      "Yes, it is secure because it has an SSL certificate."
    ],
    correctIndex: 1,
    explanation: "Scammers register lookalike domains containing brand names. Always inspect the domain core (the words right before '.com' or '.in') rather than just trusting the 'https' padlock."
  },
  {
    id: 6,
    question: "A friend on WhatsApp sends you a message saying 'I need money urgently, my phone is damaged. Send ₹5000 to this UPI ID'. What should you do?",
    options: [
      "Send the money immediately to help your friend.",
      "Call your friend on their known phone number to verify if the request is genuine.",
      "Ask them to send a voice note for verification.",
      "Ignore the message completely."
    ],
    correctIndex: 1,
    explanation: "This is a common WhatsApp impersonation scam. Always verify financial requests through a separate communication channel."
  },
  {
    id: 7,
    question: "You see a job posting on Telegram promising 'Rs 50,000 per month for part-time work - just like and share YouTube videos'. What is this?",
    options: [
      "A legitimate work-from-home opportunity in digital marketing.",
      "A task-based scam. They'll pay small amounts initially, then ask you to invest money for 'premium tasks' and disappear.",
      "A government-approved online job scheme.",
      "A genuine YouTube partnership program."
    ],
    correctIndex: 1,
    explanation: "Part-time job scams on Telegram are rampant. Initial small payments build trust, then larger 'investment' tasks lead to financial loss."
  },
  {
    id: 8,
    question: "You receive an email from 'Netflix' saying your subscription is paused and you need to update payment details by clicking a link. The email address is 'netflix-support@free-mail.com'. What do you do?",
    options: [
      "Click the link and update payment details to restore your Netflix.",
      "Check the sender email - it's from a free email provider. Netflix always uses official domains. Report as phishing.",
      "Reply to the email asking if it's genuine.",
      "Forward the email to your friends to warn them."
    ],
    correctIndex: 1,
    explanation: "Official Netflix emails come from @netflix.com. Free email providers (gmail.com, yahoo.com, etc.) in the sender address are a major red flag for phishing."
  }
];

export const LIVE_THREATS: ThreatFeedItem[] = [
  {
    id: "1",
    title: "Fake BSES Electricity Disconnection SMS",
    type: "Phishing",
    density: "High",
    target: "Metropolitan electricity consumers",
    timestamp: "Just Now",
    description: "SMS warnings claiming immediate disconnection. Scammers demand installation of remote screen-control apps to 'update bills'."
  },
  {
    id: "2",
    title: "Fake Paytm APK 'Payment Spoofer' App",
    type: "Fake App",
    density: "High",
    target: "Local retail shopkeepers & merchants",
    timestamp: "5 mins ago",
    description: "Fraudulent application showing simulated payment screenshots and simulated audio alerts of received payments to cheat shopkeepers."
  },
  {
    id: "3",
    title: "SBI YONO Lookalike 'KYC Update' Phishing Link",
    type: "Phishing",
    density: "High",
    target: "SBI Account Holders",
    timestamp: "12 mins ago",
    description: "SMS campaign warning account suspension unless users click a spoofed SBI link to enter credentials and OTP."
  },
  {
    id: "4",
    title: "'Digital Arrest' Skype Video Lures",
    type: "Social Engineering",
    density: "High",
    target: "Professionals & Senior Citizens",
    timestamp: "28 mins ago",
    description: "Scammers pretending to be CBI or Mumbai Customs Officers accusing victims of receiving illegal contraband parcels."
  },
  {
    id: "5",
    title: "FedEx Parcel Duty Pending Scam",
    type: "Phishing",
    density: "Medium",
    target: "Online Shoppers",
    timestamp: "1 hour ago",
    description: "Phishing messages claiming packages are held in warehouse, requesting a small Rs. 50 clearance payment to steal card numbers."
  },
  {
    id: "6",
    title: "WhatsApp Impersonation - Family Emergency",
    type: "Social Engineering",
    density: "High",
    target: "WhatsApp Users",
    timestamp: "2 hours ago",
    description: "Scammers clone WhatsApp accounts and message contacts asking for urgent money transfers for fake medical emergencies."
  },
  {
    id: "7",
    title: "Fake Investment App - 'SBI Wealth Pro'",
    type: "Investment Scam",
    density: "Medium",
    target: "Investors looking for high returns",
    timestamp: "3 hours ago",
    description: "Fake trading app promising 500% returns on SIP investments. Victims deposits are never returned and the app disappears."
  },
  {
    id: "8",
    title: "OLX Fake Payment Scam",
    type: "UPI Scam",
    density: "Medium",
    target: "OLX / Marketplace Sellers",
    timestamp: "4 hours ago",
    description: "Fake buyer claims to have paid via UPI and sends forged payment screenshot showing extra amount, asks for refund of difference."
  }
];

export const CYBER_NEWS: NewsItem[] = [
  {
    id: "news-1",
    title: "MHA Issues Warning Against Skype Calls Mimicking CBI and Police Officers",
    summary: "The Ministry of Home Affairs (MHA) has flagged a spike in 'Digital Arrest' cases where fraudsters hold targets under house arrest on video calls.",
    source: "PIB India",
    date: "July 04, 2026",
    category: "Alert",
    readTime: "3 min read"
  },
  {
    id: "news-2",
    title: "How to Safe-Keep your UPI Accounts: Top 5 Guidelines",
    summary: "Never share UPI pins to receive funds. Check merchant logos carefully, and do not download third-party support utilities.",
    source: "CyberSathi Guide",
    date: "June 30, 2026",
    category: "Guide",
    readTime: "5 min read"
  },
  {
    id: "news-3",
    title: "RBI Directs Banks to Tighten OTP Verification for Peer-to-Peer Transactions",
    summary: "New authentication guidelines are being proposed to check the rising frequency of SIM swapping and unauthorized fund transfers.",
    source: "Financial Express",
    date: "June 25, 2026",
    category: "News",
    readTime: "4 min read"
  },
  {
    id: "news-4",
    title: "Telegram Investment Scam Network Busted in Delhi-NCR",
    summary: "Delhi Police cyber cell dismantled a network running 'task-based' investment scams through Telegram channels targeting unemployed youth.",
    source: "Times of India",
    date: "July 02, 2026",
    category: "Alert",
    readTime: "3 min read"
  },
  {
    id: "news-5",
    title: "New WhatsApp Scam: Fake Family Member Requests Money",
    summary: "Cyber criminals are using stolen profile pictures and names to impersonate family members and request urgent money transfers.",
    source: "CyberSathi Alert",
    date: "July 01, 2026",
    category: "Alert",
    readTime: "2 min read"
  }
];

export const SCAM_ALERTS: ScamAlert[] = [
  {
    id: "alert-1",
    title: "WhatsApp OTP Verification Scam",
    description: "Scammers pose as friends/family and ask for your WhatsApp OTP to 'verify' something. Sharing OTP gives them full access to your account.",
    severity: "critical",
    date: "July 04, 2026",
    platform: "WhatsApp",
    affectedUsers: "50,000+ users",
    source: "MHA Cyber Cell"
  },
  {
    id: "alert-2",
    title: "Fake KYC Update - SBI YONO",
    description: "SMS claiming SBI YONO account will be suspended. Link leads to fake login page that steals credentials and OTP.",
    severity: "high",
    date: "July 03, 2026",
    platform: "SMS / Banking",
    affectedUsers: "1,00,000+ users",
    source: "SBI Security"
  },
  {
    id: "alert-3",
    title: "Telegram Task-Based Job Scam",
    description: "Part-time job offers on Telegram paying ₹50k/month for liking videos. Victims lured with small payments then asked to invest.",
    severity: "high",
    date: "July 02, 2026",
    platform: "Telegram",
    affectedUsers: "25,000+ users",
    source: "CyberSathi Research"
  },
  {
    id: "alert-4",
    title: "Fake Netflix Payment Phishing",
    description: "Emails claiming Netflix subscription expired. Link leads to fake payment page that steals credit card details.",
    severity: "medium",
    date: "July 01, 2026",
    platform: "Email",
    affectedUsers: "10,000+ users",
    source: "RBI Alert"
  },
  {
    id: "alert-5",
    title: "Deepfake CEO Fraud targeting Indian Companies",
    description: "AI-generated voice calls impersonating CEOs to authorize urgent fund transfers. Multiple Indian firms have reported losses.",
    severity: "critical",
    date: "June 29, 2026",
    platform: "Phone / Email",
    affectedUsers: "500+ companies",
    source: "CERT-In"
  },
  {
    id: "alert-6",
    title: "Fake OLX Payment Receipt Generator",
    description: "Fraudulent Android APK that generates fake payment success screenshots. Shopkeepers accepting UPI payments are primary targets.",
    severity: "high",
    date: "June 28, 2026",
    platform: "Android APK",
    affectedUsers: "15,000+ merchants",
    source: "CyberSathi Research"
  }
];

export const AWARENESS_ARTICLES: AwarenessArticle[] = [
  {
    id: "art-1",
    title: "Complete Guide to UPI Safety",
    summary: "Learn how to safely use UPI payments, recognize fake payment requests, and protect your bank account from fraudsters.",
    content: "UPI has revolutionized digital payments in India, but scammers are constantly finding new ways to exploit it...",
    category: "guide",
    imageUrl: "",
    readTime: "8 min read",
    author: "CyberSathi Team",
    date: "July 04, 2026"
  },
  {
    id: "art-2",
    title: "How to Identify Phishing Emails",
    summary: "Phishing emails are getting more sophisticated. Learn the 5 tell-tale signs of a phishing attempt.",
    content: "Phishing remains one of the most common cyber attack vectors. Here's how to spot them...",
    category: "article",
    imageUrl: "",
    readTime: "5 min read",
    author: "Security Experts",
    date: "July 02, 2026"
  },
  {
    id: "art-3",
    title: "Digital Arrest Scam - What You Need to Know",
    summary: "MHA has issued warnings about 'Digital Arrest' scams. Understand how they work and how to protect yourself.",
    content: "Scammers impersonate police/customs officers and conduct fake video call 'investigations'...",
    category: "video",
    imageUrl: "",
    readTime: "4 min read",
    author: "MHA Advisory",
    date: "July 01, 2026"
  },
  {
    id: "art-4",
    title: "Password Security Best Practices",
    summary: "Strong passwords are your first line of defense. Learn how to create and manage secure passwords.",
    content: "A strong password is crucial for protecting your online accounts from unauthorized access...",
    category: "guide",
    imageUrl: "",
    readTime: "6 min read",
    author: "CyberSathi Team",
    date: "June 28, 2026"
  },
  {
    id: "art-5",
    title: "WhatsApp Scams on the Rise - Stay Protected",
    summary: "New scams on WhatsApp are targeting users daily. Learn how to identify and report them.",
    content: "WhatsApp has become a hotspot for cyber fraud. From impersonation to OTP scams...",
    category: "article",
    imageUrl: "",
    readTime: "7 min read",
    author: "CyberSathi Research",
    date: "June 25, 2026"
  },
  {
    id: "art-6",
    title: "Two-Factor Authentication: Your Security Shield",
    summary: "Why 2FA is essential and how to set it up on all your important accounts.",
    content: "Two-factor authentication adds an extra layer of security to your accounts...",
    category: "guide",
    imageUrl: "",
    readTime: "5 min read",
    author: "Security Team",
    date: "June 20, 2026"
  }
];

export const SECURITY_CHECKLIST: SecurityChecklistItem[] = [
  { id: "sc-1", title: "Use strong, unique passwords", description: "Use a password manager to generate and store complex passwords for each account.", category: "password", completed: false },
  { id: "sc-2", title: "Enable Two-Factor Authentication", description: "Enable 2FA on all banking apps, email, and social media accounts.", category: "password", completed: false },
  { id: "sc-3", title: "Keep software updated", description: "Regularly update your phone OS, apps, and antivirus software.", category: "device", completed: false },
  { id: "sc-4", title: "Never share UPI PIN", description: "UPI PIN is only for sending money. Never share it even if someone claims to send you money.", category: "banking", completed: false },
  { id: "sc-5", title: "Verify caller identity", description: "If someone calls claiming to be from your bank, hang up and call the official number.", category: "social", completed: false },
  { id: "sc-6", title: "Check URL before clicking", description: "Hover over links to see the actual URL. Look for misspellings and unusual domains.", category: "general", completed: false },
  { id: "sc-7", title: "Use secure WiFi", description: "Avoid using public WiFi for banking. Use VPN if you must use public networks.", category: "network", completed: false },
  { id: "sc-8", title: "Review bank statements regularly", description: "Check your bank statements weekly for any unauthorized transactions.", category: "banking", completed: false },
  { id: "sc-9", title: "Don't download unknown APKs", description: "Only install apps from Google Play Store. Unknown APKs can contain malware.", category: "device", completed: false },
  { id: "sc-10", title: "Report fraud immediately", description: "Call 1930 within the golden hour if you become a victim of cyber fraud.", category: "general", completed: false },
  { id: "sc-11", title: "Use biometric lock on phone", description: "Enable fingerprint or face unlock on your smartphone for an extra security layer.", category: "device", completed: false },
  { id: "sc-12", title: "Be wary of urgent messages", description: "Scammers create urgency to bypass your critical thinking. Always pause and verify.", category: "social", completed: false },
  { id: "sc-13", title: "Secure social media privacy", description: "Set your social media profiles to private and avoid sharing personal information publicly.", category: "social", completed: false },
  { id: "sc-14", title: "Logout from shared devices", description: "Always logout from accounts when using shared or public computers.", category: "general", completed: false },
  { id: "sc-15", title: "Monitor credit score", description: "Regular check your credit report for any unauthorized loans or credit cards opened in your name.", category: "banking", completed: false }
];

export const FAMILY_MEMBERS: FamilyMember[] = [
  { id: "fm-1", name: "Sunita Verma", relation: "Mother", phone: "+91 98765 12345", cyberScore: 45, isActive: true, lastScan: "2 days ago" },
  { id: "fm-2", name: "Rajesh Verma", relation: "Father", phone: "+91 98765 67890", cyberScore: 55, isActive: true, lastScan: "5 days ago" },
  { id: "fm-3", name: "Priya Verma", relation: "Sister", phone: "+91 98765 11111", cyberScore: 82, isActive: false, lastScan: "1 week ago" }
];

export const NOTIFICATIONS_DATA: NotificationItem[] = [
  { id: "notif-1", title: "New Scam Alert", message: "WhatsApp OTP scam spreading rapidly. Do not share OTP with anyone.", type: "scam_alert", severity: "critical", timestamp: "30 mins ago", read: false, actionLink: "/scam-alerts" },
  { id: "notif-2", title: "Suspicious Login Detected", message: "New login from unknown device in Mumbai, Maharashtra", type: "login_alert", severity: "high", timestamp: "2 hours ago", read: false, actionLink: "/security" },
  { id: "notif-3", title: "Fraud Attempt Blocked", message: "CyberSathi blocked a phishing URL that tried to steal your SBI credentials.", type: "fraud_alert", severity: "high", timestamp: "5 hours ago", read: false, actionLink: "/dashboard" },
  { id: "notif-4", title: "Security Tip", message: "Enable 2FA on your WhatsApp account to prevent unauthorized access.", type: "tip", severity: "low", timestamp: "1 day ago", read: true, actionLink: "/awareness" },
  { id: "notif-5", title: "Password Leak Detected", message: "Your email was found in a recent data breach. Change your passwords immediately.", type: "password_leak", severity: "critical", timestamp: "2 days ago", read: true, actionLink: "/security-checklist" }
];

export const SCAM_SIMULATIONS: ScamSimulation[] = [
  {
    id: "sim-1",
    title: "Bank Call Scam",
    description: "You receive a call from 'SBI Security' saying your account has been compromised.",
    scenario: "You get a call from +91 98765-43210. Caller says: 'I am from SBI Security. Your account has been used for a fraudulent transaction of ₹45,000. To reverse this, I need your UPI PIN and the OTP sent to your phone.'",
    difficulty: "easy",
    category: "Phone Scam",
    correctAction: "Hang up immediately and call SBI official helpline 1800-123-4",
    options: [
      "Share the UPI PIN and OTP to reverse the transaction",
      "Hang up and call the official SBI helpline 1800-123-4 to verify",
      "Ask the caller for their employee ID and call them back later",
      "Transfer the money to a 'safe account' they provide"
    ],
    correctIndex: 1,
    explanation: "Banks never call to ask for UPI PIN or OTP. This is a classic vishing (voice phishing) scam.",
    tips: ["Never share OTP or PIN over phone", "Banks have caller IDs that show on official numbers", "Always call back on the number on your bank card/website"]
  },
  {
    id: "sim-2",
    title: "Fake OLX Buyer",
    description: "You're selling on OLX and a buyer sends a payment screenshot showing extra payment.",
    scenario: "You listed your phone on OLX for ₹15,000. A buyer agrees quickly and sends a 'payment screenshot' showing ₹18,500 sent. They say: 'I sent extra by mistake. Please refund ₹3,500 to this UPI ID.'",
    difficulty: "medium",
    category: "UPI Scam",
    correctAction: "Check your bank balance first. Never refund based on a screenshot.",
    options: [
      "Refund the extra ₹3,500 to the UPI ID they shared",
      "Thank them for their honesty and send the difference back",
      "Check your bank balance first. If money isn't received, it's a fake screenshot. Do not refund.",
      "Ask them to send another screenshot for confirmation"
    ],
    correctIndex: 2,
    explanation: "Fake payment screenshot generators are common. Always verify money in your account before any refund.",
    tips: ["Payment screenshots can be easily faked", "Always check bank balance before acting", "If buyer overpays, it's 99% a scam"]
  },
  {
    id: "sim-3",
    title: "WhatsApp Family Emergency",
    description: "Your 'brother' messages on WhatsApp asking for urgent money.",
    scenario: "You get a WhatsApp message from your brother's number: 'My phone got damaged and I'm using a friend's phone. I need ₹25,000 urgently for a medical emergency. Send to this UPI ID: brother@paytm. I'll return it tomorrow.'",
    difficulty: "medium",
    category: "Social Media",
    correctAction: "Call your brother on his actual number to verify the request.",
    options: [
      "Send the money immediately - it's a family emergency",
      "Call your brother on his known phone number to verify if the request is real",
      "Ask for a voice note first before sending",
      "Send half the amount and ask for confirmation"
    ],
    correctIndex: 1,
    explanation: "Scammers clone WhatsApp accounts or use SIM swap to impersonate family members. Always verify through a call.",
    tips: ["Set up two-factor authentication on WhatsApp", "Call to verify any financial request", "Have a family code word for emergencies"]
  },
  {
    id: "sim-4",
    title: "KYC Update Phishing",
    description: "SMS claiming your account will be blocked unless you update KYC.",
    scenario: "SMS from 'SBI-Bank': 'Your SBI account will be blocked in 24 hours due to incomplete KYC. Update now: https://sbi-kyc-update.cc'",
    difficulty: "easy",
    category: "Phishing",
    correctAction: "Do not click the link. Visit your bank's official website directly.",
    options: [
      "Click the link and update KYC details to avoid account block",
      "Forward the SMS to 1909 (cyber crime reporting) and delete it",
      "Call the number in the SMS to verify",
      "Share the link with family so they can also update"
    ],
    correctIndex: 1,
    explanation: "Banks send KYC reminders through official channels, never via SMS with random links. The URL is a phishing site.",
    tips: ["Official bank URLs end with .sbi or bank-specific domains", "Forward phishing SMS to 1909", "Use your bank's official app for KYC"]
  },
  {
    id: "sim-5",
    title: "QR Code Payment Scam",
    description: "A customer wants to pay via QR code at your shop.",
    scenario: "A customer at your shop wants to pay ₹500 for groceries. They insist you scan their QR code to 'receive payment'. They say: 'Just scan and enter your UPI PIN to receive the money.'",
    difficulty: "hard",
    category: "UPI Scam",
    correctAction: "You should never scan a QR code to receive money. QR codes are for sending payments.",
    options: [
      "Scan their QR code and enter your UPI PIN to receive ₹500",
      "Ask them to scan your shop's QR code instead. Scanning a QR code = SENDING money, not receiving.",
      "Scan the QR code but enter a wrong PIN first to test it",
      "Scan the QR code without entering PIN to see what happens"
    ],
    correctIndex: 1,
    explanation: "This is a common scam targeting shopkeepers. Scanning a QR code initiates a PAYMENT from your account, not a receipt.",
    tips: ["Display your own QR code prominently", "Never scan customer's QR code to receive payment", "If you scan, you SEND money"]
  },
  {
    id: "sim-6",
    title: "Investment Telegram Group",
    description: "You're added to a Telegram group offering amazing investment returns.",
    scenario: "You're added to 'SBI Wealth Pro' Telegram group. 100+ members post daily profit screenshots. Admin says: 'Limited time - invest ₹10,000 and get ₹50,000 in 7 days. Pay via UPI to this account.'",
    difficulty: "hard",
    category: "Investment Scam",
    correctAction: "Leave the group. All members except you are fake (bots). This is a classic pump-and-dump scam.",
    options: [
      "Invest ₹10,000 to test - if they pay returns, invest more",
      "Leave the group and report it. The group is full of fake accounts/bots - only you are real.",
      "Ask the admin for more proof before investing",
      "Invest small amount and withdraw immediately to test"
    ],
    correctIndex: 1,
    explanation: "These scam Telegram groups have only one real person (the victim) and hundreds of bot accounts showing fake profits.",
    tips: ["Guaranteed high returns = scam", "Check SEBI registered investment advisors", "Real investments never guarantee fixed high returns"]
  }
];

export const MOCK_SAMPLES = {
  sms: [
    {
      title: "Bank KYC Scam SMS",
      text: "Dear SBI Customer, your YONO account is suspended tonight due to pending KYC verification. Please update details now by clicking: http://yono-sbi-verification.in/secure"
    },
    {
      title: "Electricity Disconnection SMS",
      text: "ALERT! Dear electricity consumer, your power will be disconnected at 9:30 PM due to last month unpaid bill. Please contact immediate electricity division manager at 89765-42311."
    },
    {
      title: "FedEx Parcel Scam SMS",
      text: "FedEx Tracker: Your parcel containing confidential files has been held at Mumbai Custom division. Please pay clearance charges of Rs. 49 to release package: https://fedex-custom-duty-pay.org"
    }
  ],
  url: [
    {
      title: "SBI Spoofed Login",
      url: "https://www.onlinesbi-secure-update.com/login"
    },
    {
      title: "Fake Paytm Link",
      url: "https://paytm-reward-scratchcard.net/pay"
    },
    {
      title: "Official Bank Site",
      url: "https://www.onlinesbi.sbi"
    }
  ],
  email: [
    {
      title: "Spoofed HMRC/Tax Refund",
      subject: "IMMEDIATE ACTION: Outstanding Tax Refund of INR 24,500.00 Authorized",
      sender: "claims-refund@income-tax-gov-india.org",
      body: "Dear Taxpayer, our central auditing division has calculated an excess deduction on your account. You are authorized to receive INR 24,500.00 directly to your card. Please download the attached refund application, fill your credit card credentials, and click submit. Failure to claim within 48 hours results in forfeiture of refund."
    }
  ],
  voice: [
    {
      title: "Simulated Custom officer call",
      text: "I am Calling from Mumbai Custom Narcotics Department. We found a FedEx package with your Aadhaar ID containing MDMA drugs sent to Taiwan. If you do not want us to issue a non-bailable warrant, log in to this Skype call and stay in digital arrest."
    },
    {
      title: "Simulated KBC Lottery call",
      text: "Congratulations! You have won Rs 25 Lakh in Kaun Banega Crorepati lottery lucky draw. To claim your cash prize, you have to deposit Rs 12,500 in processing tax to bank manager bank details immediately."
    }
  ],
  social: [
    {
      title: "Fake Instagram Profile",
      profileUrl: "instagram.com/sbi_official_help",
      profileName: "SBI Official Help",
      followers: "2,500",
      description: "Fake customer support profile. Official SBI handle is @sbiofficial with millions of followers."
    },
    {
      title: "WhatsApp Scam Message",
      text: "Free iPhone 15 giveaway! Click this link to claim your prize: http://apple-give-away.tk"
    }
  ]
};

export const ADMIN_DASHBOARD_DATA = {
  totalUsers: 45892,
  totalScans: 128450,
  totalReports: 8245,
  fraudsPrevented: 48210,
  amountSaved: 48500000,
  activeSessions: 1284,
  threatLevel: "medium" as const,
  dailyActiveUsers: 5892,
  monthlyGrowth: 23.5
};
